version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Unit tests
          command: npm run test:unit
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Storybook Vue App
          command: npm run build-storybook
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./storybook-static
  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Deploy to Netlify
          command: curl -X POST -d {} https://api.netlify.com/build_hooks/62da092c7ae490278b9e769d
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
