version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Unit tests
          command: npm run test:unit
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Storybook Vue App
          command: npm run build-storybook
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=storybook-static
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
